version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8081:8081"
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
