version: '3'

services:
  client_frontend:
    image: baragouin/area-frontend
    container_name: client_frontend
    ports:
      - "8081:8081"
    depends_on:
      - server
      - client_mobile
    volumes:
      - shared-volume:/usr/src/app/src/shared

  server:
    image: baragouin/area-backend
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - client_mobile
    volumes:
      - shared-volume:/usr/src/app/shared

  client_mobile:
    build:
      context: ./front
      dockerfile: ./mobile/Dockerfile
    container_name: client_mobile
    volumes:
      - shared-volume:/usr/shared

volumes:
  shared-volume:
