version: '3'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: client_web
    ports:
      - "8081:8081"
    depends_on:
      - back
   #   - mobile
    volumes:
      - shared-volume:/usr/src/app/src/shared

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
   # depends_on:
     # - mobile
    volumes:
      - shared-volume:/usr/src/app/shared

 # mobile:
  #  build:
   #   context: ./front
    #  dockerfile: ./mobile/Dockerfile
    #container_name: client_mobile
    #volumes:
     # - shared-volume:/usr/shared

volumes:
  shared-volume:
