name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        chmod 600 ssh_key_rsa
        eval "$(ssh-agent)" && ssh-add ssh_key_rsa

        touch area.tar.gz
        tar --exclude='node_modules' --exclude='area.tar.gz' -czf area.tar.gz ../B-DEV-500-LYN-5-1-area-timothe.medico
        scp -o StrictHostKeyChecking=no area.tar.gz root@area.baragouin.fr:/root/dev
        ssh -o StrictHostKeyChecking=no root@area.baragouin.fr 'cd /root/dev && tar -xzf area.tar.gz && ls && cd area && docker-compose up -d --no-cache --build'

